[package]
name = "fishing"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bevy = "0.10"
bevy_atmosphere = "0.6"
smooth-bevy-cameras = "0.8"

[profile.dev]
opt-level=1
